name: Cypress Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch: {}

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      NEXT_PUBLIC_GEOQUIZ_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_GEOQUIZ_API_BASE_URL }}
      SKIP_TYPE_CHECK: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-binary-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            cypress-binary-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Verify Cypress
        run: pnpm cypress verify

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: pnpm run build
          start: pnpm start
          install: false
