name: Mystery Country Refill

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  refill:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Refill Endpoint
        run: |
          curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.API_KEY_ADMIN }}" \
            -H "Content-Type: application/json" \
            https://geoquiz.co/api/mystery-country/refill 